server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data/FunWorld.db
    initialization-mode: always
  flyway:
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
forest:
  max-connections: 1000        # 连接池最大连接数
  connect-timeout: 30000        # 连接超时时间，单位为毫秒
  read-timeout: 30000           # 数据读取超时时间，单位为毫秒
